@EportfolioAPI_HostAddress = http://localhost:5243

# Pobierz wszystkie elementy portfolio
GET {{EportfolioAPI_HostAddress}}/api/portfolio
Accept: application/json

###

# Pobierz pojedynczy element portfolio o ID 1
GET {{EportfolioAPI_HostAddress}}/api/portfolio/1
Accept: application/json
